[build]
 publish = "public"
 command = "Hugo"

[context.production.environment]
 HUGO_VERSION = "0.58.3"
 HUGO_ENABLEGITINFO = "true"
 HUGO_ENV = "production"

[context.branch-deploy.environment]
 HUGO_VERSION = "0.58.3"